# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import main_parser.parser_pb2 as parser__pb2


class ParserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListArticle = channel.unary_stream(
                '/parser.ParserService/ListArticle',
                request_serializer=parser__pb2.ListRequest.SerializeToString,
                response_deserializer=parser__pb2.ArticleList.FromString,
                )


class ParserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListArticle': grpc.unary_stream_rpc_method_handler(
                    servicer.ListArticle,
                    request_deserializer=parser__pb2.ListRequest.FromString,
                    response_serializer=parser__pb2.ArticleList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parser.ParserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ParserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/parser.ParserService/ListArticle',
            parser__pb2.ListRequest.SerializeToString,
            parser__pb2.ArticleList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
