# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parser.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparser.proto\x12\x06parser\"s\n\x0b\x41rticleList\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nsource_url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x11\n\tdate_time\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"\r\n\x0bListRequest2L\n\rParserService\x12;\n\x0bListArticle\x12\x13.parser.ListRequest\x1a\x13.parser.ArticleList\"\x00\x30\x01\x62\x06proto3')



_ARTICLELIST = DESCRIPTOR.message_types_by_name['ArticleList']
_LISTREQUEST = DESCRIPTOR.message_types_by_name['ListRequest']
ArticleList = _reflection.GeneratedProtocolMessageType('ArticleList', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLELIST,
  '__module__' : 'parser_pb2'
  # @@protoc_insertion_point(class_scope:parser.ArticleList)
  })
_sym_db.RegisterMessage(ArticleList)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'parser_pb2'
  # @@protoc_insertion_point(class_scope:parser.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

_PARSERSERVICE = DESCRIPTOR.services_by_name['ParserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ARTICLELIST._serialized_start=24
  _ARTICLELIST._serialized_end=139
  _LISTREQUEST._serialized_start=141
  _LISTREQUEST._serialized_end=154
  _PARSERSERVICE._serialized_start=156
  _PARSERSERVICE._serialized_end=232
# @@protoc_insertion_point(module_scope)
